# Render.com configuration
services:
  - type: web
    name: nido-hp
    runtime: static
    buildCommand: npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
